#!/usr/bin/env bun
// @bun
import{existsSync as w}from"fs";var n=process.argv.slice(2),$=["-hasci","-hascii","--hasci","--hascii","--h","--ha","--ah","--a"],l=(s)=>`\x1B[1m${s}\x1B[22m`;var p=(s)=>`\x1B[33m${s}\x1B[39m`,b=(s)=>`\x1B[36m${s}\x1B[39m`,x=(s)=>`\x1B[90m${s}\x1B[39m`;function S(s){let e={README_FOR_HUMAN:"     USE THE --h FLAG FOR A BETTER EXPERIENCE     ",command:"cat",description:"Read and output file contents",pos_arg_names:["files"],pos_arg_descs:["Files to read (use - for stdin)"],pos_arg_defaults:["-"],opt_arg_flags:[["-n"],["--start"],["--end"],["--ascii"],["-h","--help"]],opt_arg_descs:["Number all output lines","Line number to start reading from","Line number to stop reading at","Display output as raw text","Show this help message"]};if(s)console.log(`${l("Command:")} ${b(e.command)}`),console.log(`${e.description}
`),console.log(`${l("Usage:")} cat [options] [files...]
`),console.log(l("Positional Arguments:")),e.pos_arg_names.forEach((i,t)=>{console.log(`  ${b(i.padEnd(15))} ${e.pos_arg_descs[t]} ${x(`(default: ${e.pos_arg_defaults[t]})`)}`)}),console.log(l(`
Optional Flags:`)),e.opt_arg_flags.forEach((i,t)=>{if(i.includes("-h")||i.includes("--help"))return;let o=[...i];if(i.includes("--ascii"))o=["--a",...i];console.log(`  ${p(o.join(", ").padEnd(15))} ${e.opt_arg_descs[t]}`)}),console.log(`  ${p("--h, --ha".padEnd(15))} Show this help message`),console.log(`  ${p("--help, -h".padEnd(15))} Show this help message ${x("(JSON)")}`);else process.stdout.write(JSON.stringify(e)+`   
`)}var O=n.includes("--help")||n.includes("-h")||$.some((s)=>n.includes(s)),y=n.includes("--ascii")||$.some((s)=>n.includes(s)),r={numbers:n.includes("-n"),ascii:y},h=1,m=1/0,u=n.indexOf("--start");if(u!==-1&&n[u+1])h=parseInt(n[u+1]);var f=n.indexOf("--end");if(f!==-1&&n[f+1])m=parseInt(n[f+1]);var E=n.filter((s,e)=>{if(s==="-n"||s==="--start"||s==="--end"||s==="--ascii"||$.includes(s))return!1;if(e>0&&(n[e-1]==="--start"||n[e-1]==="--end"))return!1;if(s.startsWith("-")&&s!=="-")return!1;return!0});if(O||E.length===0&&process.stdin.isTTY)S(y),process.exit(0);var g=0;async function A(s){let e=[],i=r.numbers||(h>1||m!==1/0);for(let t of s.length>0?s:["-"])try{let o="";if(t==="-")o=await Bun.stdin.text();else{if(!w(t)){console.error(`cat: ${t}: No such file or directory`),g=1;continue}o=await Bun.file(t).text()}if(!i&&!r.ascii){if(process.stdout.write(o),!o.endsWith(`
`)&&o!=="")process.stdout.write(`
`);continue}let c=o.split(/\r?\n/);for(let a=0;a<c.length;a++){let d=a+1;if(d>=h&&d<=m){let _=c[a];if(a===c.length-1&&_===""&&o.endsWith(`
`))break;e.push({line:d,content:_})}}}catch(o){console.error(`cat: ${t}: ${o.message}`),g=1}if(e.length>0||i){if(r.ascii)e.forEach((t)=>{if(r.numbers)process.stdout.write(`${t.line.toString().padStart(6," ")}  ${t.content}
`);else process.stdout.write(`${t.content}
`)});else if(i){let t={};if(e.length>0)Object.keys(e[0]).forEach((c)=>{t[c]=e.map((a)=>a[c])});process.stdout.write(JSON.stringify(t)+`
`)}}}await A(E);process.exit(g);
